apiVersion: velero.io/v1
kind: BackupStorageLocation
metadata:
  name: primary-offsite
  namespace: velero
  labels:
    app.kubernetes.io/part-of: platform-production-cell
  annotations:
    platform.privatecloud.local/template-only: "true"
spec:
  provider: aws
  objectStorage:
    bucket: REPLACE_WITH_DEDICATED_BACKUP_BUCKET
    prefix: production-cell/REPLACE_WITH_CELL_ID
  credential:
    name: cloud-credentials
    key: cloud
  config:
    region: REPLACE_WITH_OBJECT_STORE_REGION
    s3Url: REPLACE_WITH_S3_COMPATIBLE_ENDPOINT
    s3ForcePathStyle: "true"
    checksumAlgorithm: ""
---
apiVersion: velero.io/v1
kind: VolumeSnapshotLocation
metadata:
  name: csi-primary
  namespace: velero
  labels:
    app.kubernetes.io/part-of: platform-production-cell
  annotations:
    platform.privatecloud.local/template-only: "true"
spec:
  provider: csi
  credential:
    name: cloud-credentials
    key: cloud
  config:
    region: REPLACE_WITH_OBJECT_STORE_REGION
---
apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: platform-control-plane-daily
  namespace: velero
  labels:
    app.kubernetes.io/part-of: platform-production-cell
  annotations:
    platform.privatecloud.local/template-only: "true"
spec:
  schedule: "17 2 * * *"
  template:
    ttl: 720h
    storageLocation: primary-offsite
    snapshotVolumes: true
    defaultVolumesToFsBackup: false
    includedNamespaces:
      - platform-system
      - flux-system
      - capk-system
      - kubevirt
      - rook-ceph
    labelSelector:
      matchExpressions:
        - key: platform.privatecloud.local/backup
          operator: NotIn
          values: ["disabled"]
