apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../iac/kubernetes/metallb-pool.yaml
  - ../../../iac/kubernetes/tests/pvc-test.yaml
  - ../../../iac/kubernetes/tests/lb-test.yaml
