apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - prometheus-stack-contract.yaml
  - provider-servicemonitors.yaml
  - provider-alert-rules.yaml
  - telemetry-pipeline-contract.yaml
