apiVersion: v1
kind: Namespace
metadata:
  name: observability
  labels:
    platform.privatecloud.local/observability-scope: enabled
  annotations:
    platform.privatecloud.local/template-only: "true"
