apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: provider-controller
  namespace: observability
  labels:
    platform.privatecloud.local/observability: provider
  annotations:
    platform.privatecloud.local/template-only: "true"
spec:
  namespaceSelector:
    matchNames:
      - platform-system
  selector:
    matchLabels:
      app.kubernetes.io/name: provider-controller
      app.kubernetes.io/component: controller
  endpoints:
    - port: metrics
      path: /metrics
      interval: 15s
      scrapeTimeout: 5s
      honorLabels: true
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: provider-portal
  namespace: observability
  labels:
    platform.privatecloud.local/observability: provider
  annotations:
    platform.privatecloud.local/template-only: "true"
spec:
  namespaceSelector:
    matchNames:
      - platform-system
  selector:
    matchLabels:
      app: provider-portal
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
      scrapeTimeout: 5s
      honorLabels: true
