#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"

OUT="${OUT:-${PROJECT_ROOT}/iac/kubernetes/provider-controller/sharded-controller.yaml}"
NAMESPACE="${NAMESPACE:-platform-system}"
SHARD_TOTAL="${SHARD_TOTAL:-2}"
REPLICAS_PER_SHARD="${REPLICAS_PER_SHARD:-3}"
GLOBAL_SHARD_INDEX="${GLOBAL_SHARD_INDEX:-0}"
IMAGE="${IMAGE:-localhost/platform-provider-controller:dev}"
RECONCILE_INTERVAL_SECONDS="${RECONCILE_INTERVAL_SECONDS:-15}"
LEASE_DURATION_SECONDS="${LEASE_DURATION_SECONDS:-45}"
MAX_TENANT_CLUSTER_WORKERS_PER_POOL="${MAX_TENANT_CLUSTER_WORKERS_PER_POOL:-0}"
CAPK_NODE_ROOT_STORAGE_CLASS="${CAPK_NODE_ROOT_STORAGE_CLASS:-longhorn}"
CAPK_NODE_ROOT_DISK_SIZE="${CAPK_NODE_ROOT_DISK_SIZE:-12Gi}"
CAPACITY_RESERVATION_TTL_SECONDS="${CAPACITY_RESERVATION_TTL_SECONDS:-300}"
CONTROL_PLANE_RETENTION_REAPER_INTERVAL_SECONDS="${CONTROL_PLANE_RETENTION_REAPER_INTERVAL_SECONDS:-60}"
ADMISSION_JOURNAL_RETENTION_SECONDS="${ADMISSION_JOURNAL_RETENTION_SECONDS:-604800}"
ADMISSION_JOURNAL_MAX_RECORDS_PER_PROJECT="${ADMISSION_JOURNAL_MAX_RECORDS_PER_PROJECT:-5000}"
SELF_SERVICE_AUDIT_RETENTION_SECONDS="${SELF_SERVICE_AUDIT_RETENTION_SECONDS:-604800}"
SELF_SERVICE_AUDIT_MAX_RECORDS_PER_NAMESPACE="${SELF_SERVICE_AUDIT_MAX_RECORDS_PER_NAMESPACE:-1000}"
TENANT_API_ALLOWED_CLIENT_CIDRS="${TENANT_API_ALLOWED_CLIENT_CIDRS:-172.28.10.0/24}"
TENANT_API_PROXY_NAMESPACE="${TENANT_API_PROXY_NAMESPACE:-capk-system}"
TENANT_API_PROXY_IMAGE="${TENANT_API_PROXY_IMAGE:-python:3.12-slim}"
TENANT_API_PROXY_NODE_HOSTNAMES="${TENANT_API_PROXY_NODE_HOSTNAMES:-n1,n3}"
TENANT_API_PROXY_MAX_REPLICAS="${TENANT_API_PROXY_MAX_REPLICAS:-3}"
TENANT_API_READYZ_FAILURE_THRESHOLD="${TENANT_API_READYZ_FAILURE_THRESHOLD:-3}"
TENANT_API_KUBECONFIG_INSECURE_SKIP_TLS_VERIFY="${TENANT_API_KUBECONFIG_INSECURE_SKIP_TLS_VERIFY:-true}"
METRICS_PORT="${METRICS_PORT:-8080}"

if ! [[ "${SHARD_TOTAL}" =~ ^[0-9]+$ ]] || [[ "${SHARD_TOTAL}" -lt 1 ]]; then
  echo "SHARD_TOTAL must be a positive integer, got ${SHARD_TOTAL}" >&2
  exit 1
fi
if ! [[ "${REPLICAS_PER_SHARD}" =~ ^[0-9]+$ ]] || [[ "${REPLICAS_PER_SHARD}" -lt 1 ]]; then
  echo "REPLICAS_PER_SHARD must be a positive integer, got ${REPLICAS_PER_SHARD}" >&2
  exit 1
fi
if ! [[ "${GLOBAL_SHARD_INDEX}" =~ ^[0-9]+$ ]] || [[ "${GLOBAL_SHARD_INDEX}" -ge "${SHARD_TOTAL}" ]]; then
  echo "GLOBAL_SHARD_INDEX must be in [0, SHARD_TOTAL), got ${GLOBAL_SHARD_INDEX}/${SHARD_TOTAL}" >&2
  exit 1
fi

min_available=1
if [[ "${REPLICAS_PER_SHARD}" -ge 3 ]]; then
  min_available=2
fi

mkdir -p "$(dirname "${OUT}")"

{
  cat <<YAML
# Generated by iac/scripts/render-provider-controller-shards.sh.
# Production-style active-active provider-controller shard set.
#
# Cutover rule: do not run this next to the lab single-shard Deployment unless
# the lab Deployment is scaled down or converted to the same shard topology.
# These shard Deployments reuse the base provider-controller ServiceAccount and
# RBAC from iac/kubernetes/provider-controller/rendered-controller.yaml.
YAML

  for ((index = 0; index < SHARD_TOTAL; index++)); do
    name="provider-controller-shard-${index}"
    cat <<YAML
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${name}
  namespace: ${NAMESPACE}
  labels:
    app: provider-controller
    app.kubernetes.io/name: provider-controller
    app.kubernetes.io/component: controller
    platform.privatecloud.local/controller-shard: "${index}"
spec:
  replicas: ${REPLICAS_PER_SHARD}
  selector:
    matchLabels:
      app.kubernetes.io/name: provider-controller
      app.kubernetes.io/component: controller
      platform.privatecloud.local/controller-shard: "${index}"
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: provider-controller
        app.kubernetes.io/name: provider-controller
        app.kubernetes.io/component: controller
        platform.privatecloud.local/controller-shard: "${index}"
    spec:
      serviceAccountName: provider-controller
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app.kubernetes.io/name: provider-controller
              app.kubernetes.io/component: controller
              platform.privatecloud.local/controller-shard: "${index}"
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/name: provider-controller
                    app.kubernetes.io/component: controller
                    platform.privatecloud.local/controller-shard: "${index}"
                topologyKey: kubernetes.io/hostname
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: controller
          image: ${IMAGE}
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsNonRoot: true
            runAsUser: 65532
            runAsGroup: 65532
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
          env:
            - name: RECONCILE_INTERVAL_SECONDS
              value: "${RECONCILE_INTERVAL_SECONDS}"
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: LEADER_ELECTION_LEASE_NAME
              value: ${name}
            - name: LEADER_ELECTION_LEASE_DURATION_SECONDS
              value: "${LEASE_DURATION_SECONDS}"
            - name: CONTROLLER_SHARD_TOTAL
              value: "${SHARD_TOTAL}"
            - name: CONTROLLER_SHARD_INDEX
              value: "${index}"
            - name: CONTROLLER_GLOBAL_SHARD_INDEX
              value: "${GLOBAL_SHARD_INDEX}"
            - name: CONTROLLER_NAMESPACE_ALLOWLIST
              value: ""
            - name: MAX_TENANT_CLUSTER_WORKERS_PER_POOL
              value: "${MAX_TENANT_CLUSTER_WORKERS_PER_POOL}"
            - name: CAPK_NODE_ROOT_STORAGE_CLASS
              value: ${CAPK_NODE_ROOT_STORAGE_CLASS}
            - name: CAPK_NODE_ROOT_DISK_SIZE
              value: ${CAPK_NODE_ROOT_DISK_SIZE}
            - name: CAPACITY_RESERVATION_TTL_SECONDS
              value: "${CAPACITY_RESERVATION_TTL_SECONDS}"
            - name: CONTROL_PLANE_RETENTION_REAPER_INTERVAL_SECONDS
              value: "${CONTROL_PLANE_RETENTION_REAPER_INTERVAL_SECONDS}"
            - name: ADMISSION_JOURNAL_RETENTION_SECONDS
              value: "${ADMISSION_JOURNAL_RETENTION_SECONDS}"
            - name: ADMISSION_JOURNAL_MAX_RECORDS_PER_PROJECT
              value: "${ADMISSION_JOURNAL_MAX_RECORDS_PER_PROJECT}"
            - name: SELF_SERVICE_AUDIT_RETENTION_SECONDS
              value: "${SELF_SERVICE_AUDIT_RETENTION_SECONDS}"
            - name: SELF_SERVICE_AUDIT_MAX_RECORDS_PER_NAMESPACE
              value: "${SELF_SERVICE_AUDIT_MAX_RECORDS_PER_NAMESPACE}"
            - name: TENANT_API_ALLOWED_CLIENT_CIDRS
              value: "${TENANT_API_ALLOWED_CLIENT_CIDRS}"
            - name: TENANT_API_PROXY_NAMESPACE
              value: ${TENANT_API_PROXY_NAMESPACE}
            - name: TENANT_API_PROXY_IMAGE
              value: ${TENANT_API_PROXY_IMAGE}
            - name: TENANT_API_PROXY_NODE_HOSTNAMES
              value: "${TENANT_API_PROXY_NODE_HOSTNAMES}"
            - name: TENANT_API_PROXY_MAX_REPLICAS
              value: "${TENANT_API_PROXY_MAX_REPLICAS}"
            - name: TENANT_API_READYZ_FAILURE_THRESHOLD
              value: "${TENANT_API_READYZ_FAILURE_THRESHOLD}"
            - name: TENANT_API_KUBECONFIG_INSECURE_SKIP_TLS_VERIFY
              value: "${TENANT_API_KUBECONFIG_INSECURE_SKIP_TLS_VERIFY}"
            - name: METRICS_PORT
              value: "${METRICS_PORT}"
          ports:
            - name: metrics
              containerPort: ${METRICS_PORT}
          readinessProbe:
            httpGet:
              path: /healthz
              port: metrics
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: metrics
            initialDelaySeconds: 30
            periodSeconds: 20
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: ${name}
  namespace: ${NAMESPACE}
  labels:
    app: provider-controller
    app.kubernetes.io/name: provider-controller
    app.kubernetes.io/component: controller
    platform.privatecloud.local/controller-shard: "${index}"
spec:
  minAvailable: ${min_available}
  selector:
    matchLabels:
      app.kubernetes.io/name: provider-controller
      app.kubernetes.io/component: controller
      platform.privatecloud.local/controller-shard: "${index}"
---
apiVersion: v1
kind: Service
metadata:
  name: ${name}-metrics
  namespace: ${NAMESPACE}
  labels:
    app: provider-controller
    app.kubernetes.io/name: provider-controller
    app.kubernetes.io/component: controller
    platform.privatecloud.local/controller-shard: "${index}"
spec:
  selector:
    app.kubernetes.io/name: provider-controller
    app.kubernetes.io/component: controller
    platform.privatecloud.local/controller-shard: "${index}"
  ports:
    - name: metrics
      port: ${METRICS_PORT}
      targetPort: metrics
YAML
  done
} > "${OUT}"

echo "${OUT}"
