spec:
  template:
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              preference:
                matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: NotIn
                    values:
                      - n1
      containers:
        - name: frr-k8s-statuscleaner
          resources:
            requests:
              cpu: 20m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 256Mi
          livenessProbe:
            timeoutSeconds: 5
            failureThreshold: 6
          readinessProbe:
            timeoutSeconds: 5
            failureThreshold: 6
