apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotClass
metadata:
  name: provider-production-csi-retain
  labels:
    platform.privatecloud.local/component: backup
    platform.privatecloud.local/backup-tier: production
  annotations:
    platform.privatecloud.local/template-only: "true"
driver: REPLACE_WITH_PRODUCTION_CSI_DRIVER
deletionPolicy: Retain
parameters:
  csi.storage.k8s.io/snapshotter-secret-name: REPLACE_WITH_CSI_SNAPSHOT_SECRET
  csi.storage.k8s.io/snapshotter-secret-namespace: velero
---
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotClass
metadata:
  name: provider-production-csi-delete
  labels:
    platform.privatecloud.local/component: backup
    platform.privatecloud.local/backup-tier: production
  annotations:
    platform.privatecloud.local/template-only: "true"
driver: REPLACE_WITH_PRODUCTION_CSI_DRIVER
deletionPolicy: Delete
parameters:
  csi.storage.k8s.io/snapshotter-secret-name: REPLACE_WITH_CSI_SNAPSHOT_SECRET
  csi.storage.k8s.io/snapshotter-secret-namespace: velero
