apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: tenant-volume-csi-hourly
  namespace: velero
  labels:
    app.kubernetes.io/part-of: platform-production-backup
  annotations:
    platform.privatecloud.local/template-only: "true"
spec:
  schedule: "13 * * * *"
  template:
    ttl: 168h
    storageLocation: primary-offsite
    volumeSnapshotLocations:
      - csi-primary
    snapshotVolumes: true
    defaultVolumesToFsBackup: false
    includedNamespaces:
      - REPLACE_WITH_TENANT_NAMESPACE
    includedResources:
      - persistentvolumeclaims
      - persistentvolumes
      - volumesnapshots.snapshot.storage.k8s.io
      - volumesnapshotcontents.snapshot.storage.k8s.io
      - volumes.platform.privatecloud.local
    labelSelector:
      matchExpressions:
        - key: platform.privatecloud.local/backup
          operator: NotIn
          values: ["disabled"]
---
apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: tenant-namespace-daily
  namespace: velero
  labels:
    app.kubernetes.io/part-of: platform-production-backup
  annotations:
    platform.privatecloud.local/template-only: "true"
spec:
  schedule: "31 1 * * *"
  template:
    ttl: 720h
    storageLocation: primary-offsite
    volumeSnapshotLocations:
      - csi-primary
    snapshotVolumes: true
    defaultVolumesToFsBackup: false
    includedNamespaces:
      - REPLACE_WITH_TENANT_NAMESPACE
    excludedResources:
      - events
      - events.events.k8s.io
    labelSelector:
      matchExpressions:
        - key: platform.privatecloud.local/backup
          operator: NotIn
          values: ["disabled"]
---
apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: tenant-cluster-control-plane-daily
  namespace: velero
  labels:
    app.kubernetes.io/part-of: platform-production-backup
  annotations:
    platform.privatecloud.local/template-only: "true"
spec:
  schedule: "47 2 * * *"
  template:
    ttl: 720h
    storageLocation: primary-offsite
    volumeSnapshotLocations:
      - csi-primary
    snapshotVolumes: true
    defaultVolumesToFsBackup: false
    includedNamespaces:
      - REPLACE_WITH_TENANT_NAMESPACE
      - capk-system
    includedResources:
      - kubernetesclusterclaims.platform.privatecloud.local
      - clusters.cluster.x-k8s.io
      - machines.cluster.x-k8s.io
      - machinedeployments.cluster.x-k8s.io
      - kubeadmcontrolplanes.controlplane.cluster.x-k8s.io
      - kubevirtclusters.infrastructure.cluster.x-k8s.io
      - kubevirtmachines.infrastructure.cluster.x-k8s.io
      - secrets
      - services
      - deployments.apps
      - networkpolicies.networking.k8s.io
    labelSelector:
      matchExpressions:
        - key: platform.privatecloud.local/backup
          operator: NotIn
          values: ["disabled"]
