apiVersion: kubevirt.io/v1
kind: KubeVirt
metadata:
  name: kubevirt
  namespace: kubevirt
spec:
  infra:
    replicas: 3
  workloads:
    replicas: 3
  configuration:
    developerConfiguration:
      featureGates:
        - Snapshot
  customizeComponents:
    patches:
      - resourceType: Deployment
        resourceName: virt-api
        type: strategic
        patch: '{"spec":{"strategy":{"type":"RollingUpdate","rollingUpdate":{"maxSurge":1,"maxUnavailable":1}},"template":{"spec":{"topologySpreadConstraints":[{"maxSkew":1,"topologyKey":"kubernetes.io/hostname","whenUnsatisfiable":"DoNotSchedule","labelSelector":{"matchLabels":{"kubevirt.io":"virt-api"}}}],"affinity":{"podAntiAffinity":{"requiredDuringSchedulingIgnoredDuringExecution":[{"labelSelector":{"matchLabels":{"kubevirt.io":"virt-api"}},"topologyKey":"kubernetes.io/hostname"}],"preferredDuringSchedulingIgnoredDuringExecution":[{"weight":100,"podAffinityTerm":{"labelSelector":{"matchLabels":{"kubevirt.io":"virt-api"}},"topologyKey":"kubernetes.io/hostname"}}]}}}}}}'
      - resourceType: Deployment
        resourceName: virt-controller
        type: strategic
        patch: '{"spec":{"strategy":{"type":"RollingUpdate","rollingUpdate":{"maxSurge":1,"maxUnavailable":1}},"template":{"spec":{"topologySpreadConstraints":[{"maxSkew":1,"topologyKey":"kubernetes.io/hostname","whenUnsatisfiable":"DoNotSchedule","labelSelector":{"matchLabels":{"kubevirt.io":"virt-controller"}}}],"affinity":{"podAntiAffinity":{"requiredDuringSchedulingIgnoredDuringExecution":[{"labelSelector":{"matchLabels":{"kubevirt.io":"virt-controller"}},"topologyKey":"kubernetes.io/hostname"}],"preferredDuringSchedulingIgnoredDuringExecution":[{"weight":100,"podAffinityTerm":{"labelSelector":{"matchLabels":{"kubevirt.io":"virt-controller"}},"topologyKey":"kubernetes.io/hostname"}}]}}}}}}'
      - resourceType: PodDisruptionBudget
        resourceName: virt-api-pdb
        type: strategic
        patch: '{"spec":{"minAvailable":2}}'
      - resourceType: PodDisruptionBudget
        resourceName: virt-controller-pdb
        type: strategic
        patch: '{"spec":{"minAvailable":2}}'
